### ISSUE TITLE
Max length 1000 is not sufficient

### ISSUE THREAD

**Issue by LaurensBurger** [maykinmedia/django-log-outgoing-requests#29]
https://github.com/maykinmedia/django-log-outgoing-requests/blob/272d3e933e9c9ed8ad9e1ca12d44dbc2fd0d1175/log_outgoing_requests/models.py#L19C3-L24C6

**DataError**
value too long for type character varying(1000) 

For urls with large tokens the max length of 1000 is not sufficient: 
```python
{
method: 'get', 
params: None, 
timeout: 10.0, 
url: 'https://keycloak.site.nl/realms/publiek/protocol/openid-connect/logout?id_token_hint=ey..
}
```

**Comment by sergei-maertens** [comment]
-> let's make it a `TextField` instead
