### ISSUE TITLE
Ability to configure the duration before logging settings are reverted

### ISSUE THREAD

**Issue by alextreme** [maykinmedia/django-log-outgoing-requests#33]
From LV 125, discussed with Laurens

The current RESET_DB_SAVE_AFTER configuration is 60 minutes, which is quite short if you want to investigate issues which don't happen regularly.

The request is to extend this default value to either 1 week or to make this duration configurable in the admin in order to provide sufficient insight into issues

**Comment by alextreme** [comment]
Preference would be to make the duration configurable. This so it can be kept as-is (60 minutes) as the default configuration but can be increased if an admin needs a longer duration

**Comment by stevenbal** [comment]
@alextreme is the idea here to add this to the config (default None) and if set it should override the `LOG_OUTGOING_REQUESTS_RESET_DB_SAVE_AFTER` setting?

**Comment by alextreme** [comment]
@stevenbal that is indeed how this should work
